/* =========================================================
   MONITOR — SERVICE WORKER
   Versão: v24
   - sem cache persistente
   - JSON lido diretamente pelo Worker
   - layout compacto no Quadro geral
   - corrige o link oficial da consulta SEFAZ
   - redireciona também qualquer link legado do SGP
   ========================================================= */
const CACHE_NAME="monitor-cache-v24";
const WORKER_BASE="https://monitor-sefaz-am.8dryc8ph6w.workers.dev";
self.addEventListener("install",()=>self.skipWaiting());
self.addEventListener("activate",event=>{event.waitUntil(caches.keys().then(names=>Promise.all(names.map(name=>caches.delete(name)))).then(()=>self.clients.claim()))});
async function fetchJsonDireto(request,endpoint){try{const response=await fetch(`${WORKER_BASE}/${endpoint}?t=${Date.now()}`,{method:"GET",mode:"cors",cache:"no-store",redirect:"follow"});if(response.ok){const body=await response.arrayBuffer();return new Response(body,{status:200,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store, no-cache, must-revalidate, max-age=0","Pragma":"no-cache","Expires":"0"}})}}catch(error){console.warn("Monitor: falha ao buscar JSON",endpoint,error)}return fetch(request,{cache:"no-store"})}
async function fetchPaginaComAjuste(request){const response=await fetch(request,{cache:"no-store"});if(!response.ok)return response;const contentType=response.headers.get("content-type")||"";if(!contentType.includes("text/html"))return response;let html=await response.text();
const extraCss=`<style id="quadro-geral-compacto-v24">.summary-table{min-width:660px!important}.summary-head,.summary-line{grid-template-columns:196px 68px 1fr!important;column-gap:0!important}.summary-head>div,.summary-line>div{min-width:0}.summary-head{padding:6px 8px!important;font-size:8.3px!important;line-height:1.15!important}.summary-line{padding:6px 8px!important;font-size:10.2px!important;line-height:1.18!important}.summary-num{padding-right:14px!important}.summary-sector,.summary-head>div:nth-child(2){border-left:1px solid #d8dee6;padding-left:12px!important;padding-right:4px!important}.summary-move,.summary-head>div:nth-child(3){border-left:1px solid #d8dee6;padding-left:7px!important}@media(max-width:390px){.summary-table{min-width:640px!important}.summary-head,.summary-line{grid-template-columns:190px 66px 1fr!important}.summary-head{font-size:8px!important}.summary-line{font-size:9.8px!important;padding-top:5.5px!important;padding-bottom:5.5px!important}.summary-sector,.summary-head>div:nth-child(2){padding-left:11px!important;padding-right:3px!important}.summary-move,.summary-head>div:nth-child(3){padding-left:6px!important}}</style>`;
html=html.replace(/const consulta=`https:\/\/sistemas\.sefaz\.am\.gov\.br\/sgp-am\/consulta-processo\.do\?metodo=detalhar&numeroProcesso=\$\{encodeURIComponent\(p\.numero\)\}`;/g,"const consulta=`https://online.sefaz.am.gov.br/processo/${p.numero}`;");
const fixScript=`<script id="fix-consulta-sefaz-v24">document.addEventListener('click',function(e){const b=e.target.closest('.link');if(!b)return;const card=b.closest('.card');if(!card)return;const n=card.querySelector('.num');if(!n)return;const m=n.textContent.match(/\d{2}\.\d{2}\.\d{6}\.\d{6}\/\d{4}-\d{2}/);if(!m)return;e.preventDefault();e.stopImmediatePropagation();window.location.assign('https://online.sefaz.am.gov.br/processo/'+m[0]);},true);<\/script>`;
html=html.replace("</head>",extraCss+"</head>");html=html.replace("</body>",fixScript+"</body>");return new Response(html,{status:response.status,statusText:response.statusText,headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store, no-cache, must-revalidate, max-age=0","Pragma":"no-cache","Expires":"0"}})}
self.addEventListener("fetch",event=>{if(event.request.method!=="GET")return;const url=new URL(event.request.url);
/* Proteção adicional: qualquer chamada ao endereço legado é enviada à ficha oficial atual. */
if(url.hostname==="sistemas.sefaz.am.gov.br"&&url.pathname.includes("/sgp-am/consulta-processo.do")){const numero=url.searchParams.get("numeroProcesso");if(numero){event.respondWith(Promise.resolve(Response.redirect(`https://online.sefaz.am.gov.br/processo/${numero}`,302)));return}}
if(url.origin===self.location.origin){if(url.pathname.endsWith("/dados.json")){event.respondWith(fetchJsonDireto(event.request,"dados-atualizados"));return}if(url.pathname.endsWith("/processos.json")){event.respondWith(fetchJsonDireto(event.request,"processos-atualizados"));return}if(event.request.mode==="navigate"||url.pathname.endsWith("/index.html")||url.pathname.endsWith("/Monitor-sefaz-am/")||url.pathname==="/"){event.respondWith(fetchPaginaComAjuste(event.request));return}}event.respondWith(fetch(event.request,{cache:"no-store"}))});